
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: herb-city-user-service-deployment
  namespace: herb-city-user-service-deployment
  labels:
    app: herb-city-user-service-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: herb-city-user-service-image
  template:
    metadata:
      labels:
        app: herb-city-user-service-image
    spec:
      containers:
      - name: nodeserver
        image: us-west2-docker.pkg.dev/herb-city/herb-city-user-service-repo/herb-city-user-service-image:tag
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: herb-city-user-service
  namespace: herb-city-user-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"http":"HTTP"}'
    cloud.google.com/neg-status-verbosity: "FULL"
    cloud.google.com/neg-status-uptime-checks-enable: "true"
spec:
  type: LoadBalancer
  selector:
    app: herb-city-user-service-image
  ports:
  - protocol: HTTP
    port: 80
    targetPort: 5007
    nodePort: 31110