---
apiVersion: v1
kind: Service
metadata:
  name: herb-city-user-service
spec:
  type: LoadBalancer
  selector:
    app: herb-city-user-service-image
  ports:
  - name: herb-city-user-service-port
    protocol: TCP
    port: 80
    targetPort: 5007
    nodePort: 31110
  
---

apiVersion: v1
kind: Endpoints
metadata:
  name: herb-city-user-service
subsets:
- addresses:
  - ip: 10.0.40.1
  ports:
  - name: herb-city-user-service-port
    port: 5007
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: external-service
spec:
  rules:
  - host: herb-city-user-service.com
    http:
      paths:
      - backend:
          serviceName: herb-city-user-service
          servicePort: 80
        path: /

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: herb-city-user-service-deployment
  labels:
    app: herb-city-user-service-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: herb-city-user-service-image
  template:
    metadata:
      labels:
        app: herb-city-user-service-image
    spec:
      containers:
      - name: nodeserver
        image: us-west2-docker.pkg.dev/herb-city/herb-city-user-service-repo/herb-city-user-service-image:tag
        ports:
        - containerPort: 5007