name: Deploy User Service

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Set IMAGE_TAG
      run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        gcloud auth configure-docker \us-west2-docker.pkg.dev
        docker build -t us-west2-docker.pkg.dev/herb-city/herb-city-user-service-repo/herb-city-user-service-image:${IMAGE_TAG} .
        docker push us-west2-docker.pkg.dev/herb-city/herb-city-user-service-repo/herb-city-user-service-image:${IMAGE_TAG}

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
        sed -i "s/tag/${IMAGE_TAG}/g" resources.yaml
        kubectl apply -f resources.yaml